import { Question } from "../types";

export const mustQuestions: Question[] = [
  {
    id: "loan-purpose",
    type: "select",
    title: "What is this money for?",
    description: "Purpose changes whether we steer you to a cheaper secured product.",
    required: true,
    field: "loanPurpose",
    options: [
      { label: "Wedding / personal spend", value: "personal" },
      { label: "Home purchase", value: "home" },
      { label: "Business / stock / working capital", value: "business" },
      { label: "Vehicle (including scooter)", value: "vehicle" },
      { label: "Education", value: "education" },
      { label: "Medical / emergency", value: "medical" },
      { label: "Paying other loans", value: "debt-repayment" },
      { label: "Something else", value: "other" },
    ],
    why: "A wedding personal loan and a shop LAP are not priced in the same universe.",
  },
  {
    id: "loan-amount",
    type: "currency",
    title: "How much do you want to borrow?",
    description: "The amount you have in mind — we will say if that is safe.",
    required: true,
    field: "requestedAmount",
    why: "Compared with what a lender might sanction and what your cash flow can carry. Those two are often different.",
  },
  {
    id: "loan-type",
    type: "select",
    title: "What product is the lender talking about?",
    required: true,
    field: "loanType",
    options: [
      { label: "Personal loan", value: "personal" },
      { label: "Home loan", value: "home" },
      { label: "Loan against property", value: "lap" },
      { label: "Gold loan", value: "gold" },
      { label: "Two-wheeler loan", value: "two-wheeler" },
      { label: "Business loan", value: "business" },
      { label: "Not sure — suggest one", value: "unknown" },
    ],
    why: "If you are not sure, we still pick a product. Ravi-style cases should not stay on unsecured personal.",
  },
  {
    id: "income-type",
    type: "select",
    title: "How do you earn?",
    required: true,
    field: "incomeType",
    options: [
      { label: "Salaried (payslip, TDS)", value: "salaried" },
      { label: "Self-employed / business", value: "self-employed" },
      { label: "Gig / informal / cash-variable", value: "informal" },
    ],
    why: "A kirana owner and a salaried engineer do not see the same follow-up questions, and FOIR caps differ.",
  },
  {
    id: "monthly-income",
    type: "currency",
    title: "Usual monthly take-home?",
    description: "What actually lands in a typical month, after PF/tax. If income swings, use a typical month — not the best month.",
    required: true,
    field: "monthlyIncome",
    why: "Starting point for FOIR and for leftover cash after expenses.",
  },
  {
    id: "existing-emi",
    type: "currency",
    title: "Existing loan EMIs each month?",
    description: "All EMIs you already pay. Enter 0 if none. Do not count rent here.",
    required: true,
    field: "existingEMI",
    why: "Headroom is income minus this, not income.",
  },
  {
    id: "household-expenses",
    type: "currency",
    title: "Usual household spend each month?",
    description: "Rent, food, school, utilities, travel — not EMIs.",
    required: true,
    field: "householdExpenses",
    why: "Lenders often ignore this. You should not. It is why 'their number' and 'your number' diverge.",
  },
  {
    id: "age",
    type: "number",
    title: "Your age?",
    required: true,
    field: "age",
    why: "Caps how long a loan can run, which changes EMI.",
  },
  {
    id: "credit-score",
    type: "select",
    title: "Do you know your credit score?",
    description: "CIBIL / Experian / CRIF. If you have never borrowed, pick I don't know — that is not a 300.",
    required: true,
    field: "creditScoreBand",
    options: [
      { label: "750 or above", value: "750+" },
      { label: "700–749", value: "700-749" },
      { label: "650–699", value: "650-699" },
      { label: "Below 650", value: "below-650" },
      { label: "I don't know / no score yet", value: "unknown" },
    ],
    why: "Unknown keeps a wide rate band. It is not treated as the worst score.",
  },
];
